### PR TITLE
Allows for single and double tap on each post

### PR DESCRIPTION
**Pull request by banaslee**
Fixes https://github.com/carson-katri/reddit-swiftui/issues/9

Quite a lot of changes in order to achieve this:
- had to activate the navigation link programmatically in order to capture single and double tap
- NavigationLink activated based on new view state for selected post tag
- moved the RequestView to the ContentView so the selected post wouldn't reload the whole PostList and repeat the request
- PostList now initialised with Listing object
- setting the contentShape of the PostView in the list in order to capture hits in the whole area, otherwise it would land on the NavigationLink behind
- adding two tap gestures in order of precedence
- set the default frame for the new spinner to guarantee a minimum size while loading

The only secondary effect from this solution I wasn't able to fix is that now cells don't get a selected state like before. Hopefully someone knows how to fix that, otherwise can be a good bug to follow up with.

### CODE REVIEW

**Comment by carson-katri** [comment]
Maybe for now fake the selection with a `.background(Color.blue)`?

**Comment by banaslee** [comment]
Got selection state but unfortunately is not blue like before with NavigationLink.
Quite lost actually. Selection seems to be different than highlighting but I'm now starting to understand why people complain about SwiftUI documentation :)

**Comment by banaslee** [comment]
Couldn't get a blue selection after many tries but there's a strange bug:

1. select a post
2. see the post now has a grey selected background
3. tap section header
4. see the selected post now has a blue selected background
5. all consecutive selections will have a blue background as well

I'm throwing the towel on this one :)

**Comment by carson-katri** [comment]
This looks really good, but there is one issue 😂 

If you click on the edge (outside the text or images), it gives a blue highlight but doesn't actually show the page. Could you push the clickable area all the way up to the edge so they can't select that?

Hopefully Apple releases some fixes for this stuff in a few weeks with macOS 10.16

**Comment by banaslee** [comment]
I’ll give it a try. 

But if these are the only issues I propose it’s merged and new issues get opened. Can become good issues for first contributors.

**Comment by carson-katri** [comment]
Ok, I’ll merge now. Great work

**Pull request merged**
